version: "3.6"
services:
  es6:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.0
    container_name: es6
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - es
  kb6:
    image: docker.elastic.co/kibana/kibana:6.7.0
    container_name: kb6
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "5601:5601"
    networks:
      - es
    depends_on:
      - es6
networks:
  es:
    driver: bridge
