version: '3.6'
services:
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    ports:
      - 8125:8125/udp
    networks:
      - tig
    depends_on: 
      - influxdb
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    environment:
      INFLUXDB_DB: grafana
    ports:
      - 8083:8083
      - 8086:8086
    networks:
      - tig
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      GF_SERVER_ROOT_URL: "http://localhost"
      GF_SECURITY_ADMIN_PASSWORD: "password"
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
    ports:
      - 3000:3000
    networks:
      - tig
    depends_on: 
      - influxdb
networks:
  tig:
    driver: bridge
